# Generated by Django 3.1.2 on 2020-10-16 22:52

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='the child name')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image')),
                ('text', models.TextField(verbose_name='vey brief card text')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stage_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='the author')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('stage_number', models.IntegerField(verbose_name='the stage number')),
                ('text', models.TextField(verbose_name='the text')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image')),
                ('image_text', models.TextField(verbose_name='the image accompanying text')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_content', to='cards_system.child')),
            ],
        ),
    ]
