# Generated by Django 3.1.2 on 2020-10-17 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='text',
        ),
        migrations.AlterField(
            model_name='child',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date the card is put in use'),
        ),
        migrations.AlterField(
            model_name='stage_content',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stage_content',
            name='text',
            field=models.TextField(verbose_name='the stage text'),
        ),
    ]
