# Generated by Django 3.1.2 on 2020-10-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_system', '0002_auto_20201017_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='current_stage',
            field=models.IntegerField(default=0, verbose_name='Stage to be used as current when the card is inserted'),
        ),
    ]
