# Generated by Django 3.1.2 on 2020-10-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_system', '0003_child_current_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage_content',
            name='image_text_es',
            field=models.TextField(default='nada', verbose_name='the image accompanying Spanish text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage_content',
            name='text_es',
            field=models.TextField(default='nada', verbose_name='the stage Spanish text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage_content',
            name='image_text',
            field=models.TextField(verbose_name='the image accompanying English text'),
        ),
        migrations.AlterField(
            model_name='stage_content',
            name='text',
            field=models.TextField(verbose_name='the stage Englishtext'),
        ),
    ]
